// Generated by CoffeeScript 2.0.0-beta4
(function() {
  var app, somata_socketio;

  somata_socketio = require('../');

  app = somata_socketio({
    port: 20002
  });

  app.get('/', function(req, res) {
    return res.render('base');
  });

  app.start();

}).call(this);
